name: Deploy

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
  - cron: "23 4 5 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.0, 8.1, 8.2 ]
        nextcloud-version-branch: [ stable24, stable25, stable26 ]  # see https://github.com/nextcloud/server/branches
        exclude:
          - php-version: 8.2
            nextcloud-version-branch: stable24
          - php-version: 8.2
            nextcloud-version-branch: stable25

    name: NC ${{matrix.nextcloud-version-branch}} on PHP ${{ matrix.php-version }}
    env:
      DB_DATABASE: oc_autotest
      DB_ROOT: root

    steps:
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -u${{ env.DB_ROOT }} -p${{ env.DB_ROOT }} -e 'CREATE DATABASE ${{ env.DB_DATABASE }};'
          mysql -u${{ env.DB_ROOT }} -p${{ env.DB_ROOT }} -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"
          mysql -u${{ env.DB_ROOT }} -p${{ env.DB_ROOT }} -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"

      - uses: actions/checkout@v3
        name: Checkout Nextcloud ${{matrix.nextcloud-version-branch}}
        with:
          repository: nextcloud/server
          ref: ${{matrix.nextcloud-version-branch}}
          fetch-depth: 1
          submodules: true  # 'Composer autoloader' is required in order to run the code check

      - uses: actions/checkout@v3
        name: Add switchboardbridge to nextcloud
        with:
          path: apps/switchboardbridge

      - name: Install npm dependencies for switchboardbridge
        run: |
          cd apps/switchboardbridge
          npm install --force

      - name: Install PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-file: apps/switchboardbridge/tests/php.ini
          tools: phpunit:9.5, phpcs, phpcbf

      - name: Configure NC
        run: |
          mkdir data
          ./occ maintenance:install --database-name $DB_DATABASE --database-user oc_autotest --admin-user admin --admin-pass admin --database mysql --database-pass=''

      - name: Deploy switchboardbridge plugin
        run: |
          ./occ app:enable switchboardbridge

      - name: Style checking
        continue-on-error: true
        run: |
          cd apps/switchboardbridge
          npx stylelint css/*.css
      - name: Fix Style Lint
        continue-on-error: true
        run: |
          cd apps/switchboardbridge
          npx stylelint css/*.css --fix

      - name: Js Lint checking
        continue-on-error: true
        run: |
          cd apps/switchboardbridge
          npx eslint --ext .js .
      - name: Fix Js Lint
        continue-on-error: true
        run: |
          cd apps/switchboardbridge
          npx eslint --fix --ext .js .

      - name: PHP lint
        continue-on-error: true
        run: |
          cd apps/switchboardbridge
          phpcs --extensions=php --ignore=*/tests/*,*/node_modules/* . 

      - name: PHP lint fix
        continue-on-error: true
        run: |
          cd apps/switchboardbridge
          phpcbf --extensions=php --ignore=*/tests/*,*/node_modules/* .
 
      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: apps/switchboardbridge
          file_pattern: '*.php *.js *.css'
          disable_globbing: true
          commit_message: Apply PHP, CSS and JS auto fix changes
